/*
  Warnings:

  - You are about to drop the `Project` table. If the table is not empty, all the data it contains will be lost.

*/
-- DropTable
DROP TABLE "Project";

-- CreateTable
CREATE TABLE "Study_Data" (
    "id" TEXT NOT NULL,
    "project_id" TEXT NOT NULL,
    "project_id_external" TEXT NOT NULL,
    "project_name" TEXT NOT NULL,
    "project_contact" TEXT NOT NULL,
    "project_description" TEXT NOT NULL,
    "type" TEXT NOT NULL,
    "license" TEXT NOT NULL,
    "citation" TEXT,
    "keywords" TEXT,
    "associated_parties" TEXT,
    "study_area_description" TEXT,
    "external_links" TEXT,
    "recordedBy" TEXT,
    "sampling_description" TEXT,
    "grant_number" TEXT,
    "grant_title" TEXT,
    "grant_agency" TEXT,
    "project_proposal" TEXT,
    "accessions" TEXT,
    "metadata_notes" TEXT,
    "date_modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" TEXT NOT NULL,

    CONSTRAINT "Study_Data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Water_Sample_Data" (
    "id" TEXT NOT NULL,
    "sample_name" TEXT NOT NULL,
    "serial_number" TEXT,
    "cruise_id" TEXT,
    "line_id" TEXT,
    "station" TEXT,
    "locationID" TEXT,
    "ctd_bottle_no" TEXT,
    "sample_replicate" TEXT,
    "source_mat_id" TEXT,
    "biological_replicates" TEXT,
    "extract_number" TEXT,
    "sample_title" TEXT,
    "bioproject_accession" TEXT,
    "notes_sampling" TEXT,
    "project_id" TEXT,
    "aplicon_sequenced" TEXT,
    "metagenome_sequence" TEXT,
    "organism" TEXT NOT NULL,
    "collection_date_local" TIMESTAMP(3),
    "collection_date" TIMESTAMP(3) NOT NULL,
    "depth" DOUBLE PRECISION NOT NULL,
    "minimumDepthInMeters" DOUBLE PRECISION,
    "maximumDepthInMeters" DOUBLE PRECISION,
    "env_broad_scale" TEXT NOT NULL,
    "env_local_scale" TEXT NOT NULL,
    "env_medium" TEXT NOT NULL,
    "geo_loc_name" TEXT NOT NULL,
    "waterBody" TEXT,
    "countryCode" TEXT,
    "lat_lon" TEXT NOT NULL,
    "decimalLatitude" DOUBLE PRECISION,
    "decimalLongitude" DOUBLE PRECISION,
    "geodeticDatum" TEXT,
    "samp_vol_we_dna_ext" TEXT,
    "samp_collect_device" TEXT,
    "samp_mat_process" TEXT,
    "size_frac" TEXT,
    "dna_conc" TEXT,
    "concentrationUnit" TEXT,
    "sample_type" TEXT,
    "collection_method" TEXT,
    "basisOfRecord" TEXT,
    "alkalinity" TEXT,
    "alkalinity_method" TEXT,
    "alkyl_diethers" TEXT,
    "altitude" TEXT,
    "aminopept_act" TEXT,
    "ammonium" TEXT,
    "atmospheric_data" TEXT,
    "bac_prod" TEXT,
    "bac_resp" TEXT,
    "bacteria_carb_prod" TEXT,
    "biomass" TEXT,
    "bishomohopanol" TEXT,
    "bromide" TEXT,
    "calcium" TEXT,
    "carb_nitro_ratio" TEXT,
    "chem_administration" TEXT,
    "chloride" TEXT,
    "chlorophyll" TEXT,
    "conduc" TEXT,
    "density" DOUBLE PRECISION,
    "diether_lipids" TEXT,
    "diss_carb_dioxide" TEXT,
    "diss_hydrogen" TEXT,
    "diss_inorg_carb" TEXT,
    "diss_inorg_nitro" TEXT,
    "diss_inorg_phosp" TEXT,
    "diss_org_carb" TEXT,
    "diss_org_nitro" TEXT,
    "diss_oxygen" TEXT,
    "down_par" TEXT,
    "elev" DOUBLE PRECISION,
    "fluor" TEXT,
    "glucosidase_act" TEXT,
    "isolation_source" TEXT,
    "light_intensity" TEXT,
    "magnesium" TEXT,
    "mean_frict_vel" DOUBLE PRECISION,
    "mean_peak_frict_vel" DOUBLE PRECISION,
    "misc_param" TEXT,
    "n_alkanes" TEXT,
    "neg_cont_type" TEXT,
    "nitrate" TEXT,
    "nitrite" TEXT,
    "nitro" TEXT,
    "omics_observ_id" TEXT,
    "org_carb" TEXT,
    "org_matter" TEXT,
    "org_nitro" TEXT,
    "organism_count" TEXT,
    "oxy_stat_samp" TEXT,
    "part_org_carb" TEXT,
    "part_org_nitro" TEXT,
    "perturbation" TEXT,
    "petroleum_hydrocarb" TEXT,
    "ph" TEXT,
    "phaeopigments" TEXT,
    "phosphate" TEXT,
    "phosplipid_fatt_acid" TEXT,
    "photon_flux" TEXT,
    "pos_cont_type" TEXT,
    "potassium" TEXT,
    "pressure" TEXT,
    "primary_prod" TEXT,
    "redox_potential" TEXT,
    "rel_to_oxygen" TEXT,
    "salinity" TEXT,
    "samp_store_dur" TEXT,
    "samp_store_loc" TEXT,
    "samp_store_temp" TEXT,
    "silicate" TEXT,
    "size_frac_low" TEXT,
    "size_frac_up" TEXT,
    "sodium" TEXT,
    "soluble_react_phosp" TEXT,
    "source_material_id" TEXT,
    "sulfate" TEXT,
    "sulfide" TEXT,
    "suspend_part_matter" TEXT,
    "temp" TEXT,
    "tidal_stage" TEXT,
    "tot_depth_water_col" TEXT,
    "tot_diss_nitro" TEXT,
    "tot_inorg_nitro" TEXT,
    "tot_nitro" TEXT,
    "tot_part_carb" TEXT,
    "tot_phosp" TEXT,
    "turbidity" TEXT,
    "water_current" TEXT,
    "description" TEXT,
    "date_modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" TEXT NOT NULL,

    CONSTRAINT "Water_Sample_Data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Amplicon_PrepData" (
    "id" TEXT NOT NULL,
    "sample_name" TEXT NOT NULL,
    "library_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "library_strategy" TEXT NOT NULL,
    "library_source" TEXT NOT NULL,
    "library_selection" TEXT NOT NULL,
    "lib_layout" TEXT NOT NULL,
    "platform" TEXT NOT NULL,
    "instrument_model" TEXT NOT NULL,
    "design_description" TEXT NOT NULL,
    "filetype" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "filename2" TEXT,
    "drive_location" TEXT NOT NULL,
    "biosample_accession" TEXT,
    "sra_accession" TEXT,
    "date_dna_extracted" TIMESTAMP(3) NOT NULL,
    "extraction_personnel" TEXT NOT NULL,
    "date_pcr" TIMESTAMP(3) NOT NULL,
    "pcr_personnel" TEXT NOT NULL,
    "seq_facility" TEXT,
    "seq_meth" TEXT,
    "nucl_acid_ext" TEXT,
    "amplicon_sequenced" TEXT,
    "target_gene" TEXT,
    "target_subfragment" TEXT,
    "pcr_primer_forward" TEXT,
    "pcr_primer_reverse" TEXT,
    "pcr_primer_name_forward" TEXT,
    "pcr_primer_name_reverse" TEXT,
    "pcr_primer_reference" TEXT,
    "pcr_cond" TEXT,
    "nucl_acid_amp" TEXT,
    "adapters" TEXT,
    "mid_barcode" TEXT,
    "date_modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" TEXT NOT NULL,

    CONSTRAINT "Amplicon_PrepData_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Metag_Prep_Data" (
    "id" TEXT NOT NULL,
    "sample_name" TEXT NOT NULL,
    "library_id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "library_strategy" TEXT NOT NULL,
    "library_source" TEXT NOT NULL,
    "library_selection" TEXT NOT NULL,
    "lib_layout" TEXT NOT NULL,
    "platform" TEXT NOT NULL,
    "instrument_model" TEXT NOT NULL,
    "design_description" TEXT NOT NULL,
    "filetype" TEXT NOT NULL,
    "filename" TEXT NOT NULL,
    "filename2" TEXT,
    "drive_location" TEXT NOT NULL,
    "biosample_accession" TEXT,
    "sra_accession" TEXT,
    "seq_facility" TEXT,
    "nucl_acid_ext" TEXT,
    "nucl_acid_amp" TEXT,
    "adapters" TEXT,
    "mid_barcode" TEXT,
    "seq_meth" TEXT,
    "tax_class" TEXT,
    "date_modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" TEXT NOT NULL,

    CONSTRAINT "Metag_Prep_Data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Analysis_Data" (
    "id" TEXT NOT NULL,
    "amplicon_sequenced" TEXT NOT NULL,
    "ampliconSize" INTEGER,
    "trim_method" TEXT,
    "cluster_method" TEXT,
    "pid_clustering" TEXT,
    "taxa_class_method" TEXT NOT NULL,
    "taxa_ref_db" TEXT NOT NULL,
    "assembly_qual" TEXT,
    "assembly_software" TEXT,
    "annot" TEXT,
    "number_contig" INTEGER,
    "code_repo" TEXT NOT NULL,
    "sop" TEXT,
    "identificationReferences" TEXT NOT NULL,
    "controls_used" TEXT,
    "compl_score" TEXT,
    "compl_software" TEXT,
    "compl_appr" TEXT,
    "contam_score" TEXT,
    "contam_screen_input" TEXT,
    "contam_screen_param" TEXT,
    "decontam_software" TEXT,
    "bin_param" TEXT,
    "bin_software" TEXT,
    "reassembly_bin" TEXT,
    "mag_cov_software" TEXT,
    "date_modified" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "modified_by" TEXT NOT NULL,

    CONSTRAINT "Analysis_Data_pkey" PRIMARY KEY ("id")
);

-- CreateTable
CREATE TABLE "Measurement_Metadata" (
    "id" TEXT NOT NULL,

    CONSTRAINT "Measurement_Metadata_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Study_Data_project_id_key" ON "Study_Data"("project_id");
