# Use the tourmaline image as a parent image, which uses the official QIIME 2 image
FROM aomlomics/tourmaline:latest

# Label information
LABEL maintainer="Carter Rollins"
LABEL description="Docker image to build the Opal server for handling Tourmaline/QIIME2 requests."

# Allow statements and log messages to immediately appear in the logs
ENV PYTHONUNBUFFERED True

# Update apt and install screen
RUN apt-get update && apt-get install -y screen

# Install Python dependencies
COPY server/requirements.txt app/server/requirements.txt
RUN pip install --no-cache-dir -r app/server/requirements.txt

# Copy local code to the container image
WORKDIR /app
COPY . ./
WORKDIR /app/server

# Generate prisma client
RUN prisma generate --generator py

# Run the web service on container startup on port 8080, as per Google Cloud Run's Container runtime contract.
# Here we use gunicorn with the uvicorn ASGI worker class.
# We use a screen to reattach to the process later.
CMD exec screen -S opalserver gunicorn --pid app.pid --bind :8080 --workers 1 --threads 8 --timeout 0 -k uvicorn.workers.UvicornWorker main:app
